web:
  # basic nginx container using the official docker image
  # accessible at port 8080 on localhost
  # ./code contains the html/php/css/etc.
  # edit ./site.conf to configure nginx
  # linked to php-ivg for php processing

  image: nginx:latest
  ports:
  - "80:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  # basic php contianer derived from official docker image
  # ./php_image/dockerfile is used to add GD and MYSQLI extensions
  # ./code contains the html/php/css/etc.
  # linked to mysql database (db)

  build: ./php_image
  volumes:
    - ./code:/code
    - ./secure:/secure